#!/usr/bin/env bash
# lib/core/completion.sh — workbench-core
#
# Generates bash/zsh tab-completion scripts for the 'wb' CLI itself
# (Phase 1: top-level subcommand completion only — no argument-level
# completion of module/tool/bundle names yet; see ARCHITECTURE.md §12
# D44 for the follow-up this deliberately defers). Command names are
# never hand-maintained here: they're introspected straight out of
# bin/wb's own dispatch case statement, the same plain-text-introspection
# technique _extract_function_names already uses for register.shell
# content (lib/core/functions.sh) — so this list can never drift from
# what 'wb' actually dispatches on.

# shellcheck source=lib/core/log.sh
_wb_completion_dir="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" && pwd)"
[[ -f "${_wb_completion_dir}/log.sh" ]] && source "${_wb_completion_dir}/log.sh"
unset _wb_completion_dir

# shellcheck disable=SC2015
command -v _workbench_register_script_version &>/dev/null && _workbench_register_script_version "lib/core/completion.sh" "0.2.0" || true

# _wb_completion_dispatch_commands
# Prints one dispatch-case command per line, in source order, by reading
# bin/wb's own `case "${_wb_cmd}" in ... esac` block as plain text. Never
# sources bin/wb — introspection only. The regex requires a leading
# lowercase letter, which naturally excludes both the `-h|--help|"")`
# and `*)` branches without special-casing them.
_wb_completion_dispatch_commands() {
    local wb_src="${WB_ROOT}/bin/wb"
    if [[ ! -f "${wb_src}" ]]; then
        log_error "wb completion: can't find bin/wb at '${wb_src}' to introspect"
        return 1
    fi
    awk '
        /^case "\$\{_wb_cmd\}" in$/ { in_case=1; next }
        in_case && /^esac$/ { in_case=0 }
        in_case { print }
    ' "${wb_src}" \
        | grep -oE '^[[:space:]]*[a-z][a-zA-Z0-9_-]*\)' \
        | tr -d ' )'
}

# _wb_completion_generate_bash
_wb_completion_generate_bash() {
    local commands
    # paste -s (not `tr '\n' ' '`) so the joined list has no trailing
    # space — a trailing space would leave compgen -W an empty extra word.
    commands="$(_wb_completion_dispatch_commands | paste -sd' ' -)"
    cat <<EOF
# Generated by 'wb completion bash' — do not hand-edit, re-run to refresh.
_wb_completions() {
    local cur
    cur="\${COMP_WORDS[COMP_CWORD]}"
    if [[ \${COMP_CWORD} -eq 1 ]]; then
        # shellcheck disable=SC2207
        COMPREPLY=( \$(compgen -W "${commands}" -- "\${cur}") )
    else
        COMPREPLY=()
    fi
}
complete -F _wb_completions wb
EOF
}

# _wb_completion_generate_zsh
_wb_completion_generate_zsh() {
    local commands
    commands="$(_wb_completion_dispatch_commands | paste -sd' ' -)"
    cat <<EOF
# Generated by 'wb completion zsh' — do not hand-edit, re-run to refresh.
_wb_completions() {
    local -a commands
    commands=(${commands})
    _describe 'wb command' commands
}
if command -v compdef &>/dev/null; then
    compdef _wb_completions wb
fi
EOF
}

# _wb_cmd_completion <bash|zsh>
_wb_cmd_completion() {
    local shell="${1:-}"
    case "${shell}" in
        bash) _wb_completion_generate_bash ;;
        zsh)  _wb_completion_generate_zsh ;;
        "")
            log_error "wb completion: usage: wb completion bash|zsh"
            return 2
            ;;
        *)
            log_error "wb completion: unsupported shell '${shell}' — only bash and zsh are supported (ARCHITECTURE.md D4: no Windows/PowerShell)"
            return 2
            ;;
    esac
}
