#!/usr/bin/env bash
# lib/ssh/bootstrap.sh — SSH deploy-key + alias mechanics.
#
# Ported from workbench-precursor's install.sh Phase 3 (generate_deploy_key,
# _write_ssh_host_entry, ensure_ssh_config_include, setup_ssh_keys),
# generalised from a fixed EXTERNAL_REPO_* array collected interactively to
# any currently-registered private module (ARCHITECTURE.md §3/D1). This now
# serves two purposes, not the original one: the original bootstrap use case
# (a private repo needs a deploy key before anything can sync it at all),
# and it is the direct dependency of Phase 5's private-repo distribution
# path (`lib/distribution/fetch-git-snapshot.sh`'s `git ls-remote`/shallow
# clone, which needs the alias's HostName+IdentityFile to already resolve).
#
# Gated exactly as before: a clean no-op the moment zero modules are
# registered as PRIVATE=true. No `workbench-*` repo is ever private (§2), so
# core itself never triggers this path.

_wb_ssh_lib_dir="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" && pwd)"
# shellcheck source=lib/sync/state.sh
[[ -f "${_wb_ssh_lib_dir}/../sync/state.sh" ]] && source "${_wb_ssh_lib_dir}/../sync/state.sh"

# shellcheck disable=SC2015
command -v _workbench_register_script_version &>/dev/null && _workbench_register_script_version "lib/ssh/bootstrap.sh" "0.1.0" || true

WORKBENCH_SSH_CONFIG_D_FILE="${HOME:-}/.ssh/config.d/10-workbench.conf"

# workbench_ssh_extract_host <url>
# Derives the real git host from a URL in any of https://host/path,
# git@host:path, ssh://git@host/path form. Empty (exit 1) on no match —
# callers decide the fallback. A "host" that is itself a workbench-<name>
# alias (already rewritten) is treated as unresolved, same reasoning as the
# donor script: the real host isn't recoverable from an alias.
workbench_ssh_extract_host() {
    local url="$1" host=""
    if [[ "${url}" =~ ^https://([^/]+)/ ]]; then
        host="${BASH_REMATCH[1]}"
    elif [[ "${url}" =~ ^ssh://git@([^/]+)/ ]]; then
        host="${BASH_REMATCH[1]}"
    elif [[ "${url}" =~ ^git@([^:]+): ]]; then
        host="${BASH_REMATCH[1]}"
    fi
    [[ "${host}" =~ ^workbench- ]] && host=""
    [[ -z "${host}" ]] && return 1
    printf '%s\n' "${host}"
}

# workbench_ssh_extract_path <url>
# The owner/repo(.git) portion following the host, from any of the three
# accepted URL forms — this is what gets preserved when rewriting to the
# alias form.
workbench_ssh_extract_path() {
    local url="$1" path=""
    if [[ "${url}" =~ ^https://[^/]+/(.+)$ ]]; then
        path="${BASH_REMATCH[1]}"
    elif [[ "${url}" =~ ^ssh://git@[^/]+/(.+)$ ]]; then
        path="${BASH_REMATCH[1]}"
    elif [[ "${url}" =~ ^git@[^:]+:(.+)$ ]]; then
        path="${BASH_REMATCH[1]}"
    fi
    [[ -z "${path}" ]] && return 1
    printf '%s\n' "${path}"
}

# workbench_ssh_key_name <module>
workbench_ssh_key_name() { printf 'workbench-%s\n' "$1"; }
# workbench_ssh_alias <module>
workbench_ssh_alias() { printf 'workbench-%s\n' "$1"; }

# workbench_ssh_generate_deploy_key <key_name> <comment>
workbench_ssh_generate_deploy_key() {
    local key_name="$1" comment="$2"
    local key_path="${HOME}/.ssh/${key_name}"

    if [[ -f "${key_path}" ]]; then
        log_info "Deploy key '${key_name}' already exists — skipping generation."
        return 0
    fi

    mkdir -p "${HOME}/.ssh"
    chmod 700 "${HOME}/.ssh"
    ssh-keygen -t ed25519 -f "${key_path}" -N "" -C "${comment}" -q
    log_info "Generated deploy key: ${key_path}"
}

_wb_ssh_write_host_entry() {
    local alias="$1" key_name="$2" conf_file="$3" host="$4"
    cat >> "${conf_file}" << EOF

Host ${alias}
    HostName ${host}
    User git
    IdentityFile ${HOME}/.ssh/${key_name}
    IdentitiesOnly yes
    ControlMaster no
    ControlPersist no
    ControlPath none
EOF
}

# workbench_ssh_ensure_config_include
# Ensures ~/.ssh/config sources ~/.ssh/config.d/*.conf — idempotent, adds
# the Include directive at most once.
workbench_ssh_ensure_config_include() {
    local ssh_config="${HOME}/.ssh/config"
    local include_line="Include ~/.ssh/config.d/*.conf"

    mkdir -p "${HOME}/.ssh"
    touch "${ssh_config}"
    chmod 600 "${ssh_config}"

    grep -qF "${include_line}" "${ssh_config}" 2>/dev/null && return 0

    local tmp
    tmp="$(mktemp "${ssh_config}.XXXXXX")"
    { echo "${include_line}"; echo ""; cat "${ssh_config}"; } > "${tmp}"
    mv "${tmp}" "${ssh_config}"
    chmod 600 "${ssh_config}"
    log_info "Added Include directive to ~/.ssh/config"
}

_wb_ssh_ensure_conf_file() {
    local conf_file="$1"
    mkdir -p "$(dirname "${conf_file}")"
    chmod 700 "$(dirname "${conf_file}")"
    [[ -f "${conf_file}" ]] && return 0
    cat > "${conf_file}" << 'EOF'
# workbench-core private-module deploy keys — generated by `wb install`/
# `wb apply` (lib/ssh/bootstrap.sh). One Host alias per private module.
# IdentitiesOnly yes prevents SSH falling back to any other loaded key.
#
# Alias format: workbench-<module-name> (works for any git host). The
# module's REPO_URL in sync.conf is rewritten to this alias form the first
# time this runs for it — nothing else needs to change to use it.
EOF
    chmod 600 "${conf_file}"
}

# workbench_ssh_bootstrap_module <name>
# Idempotent: generates the deploy key and config.d alias for one private
# module if not already done, and rewrites its sync.conf REPO_URL to the
# alias form. A no-op if the module isn't PRIVATE=true, or its REPO_URL is
# already in alias form.
workbench_ssh_bootstrap_module() {
    local name="$1"
    local private url
    private="$(workbench_module_conf_get "${name}" PRIVATE false)"
    [[ "${private}" == "true" ]] || return 0

    url="$(workbench_module_conf_get "${name}" REPO_URL "")"
    [[ -z "${url}" ]] && { log_warn "workbench_ssh_bootstrap_module: ${name}: no REPO_URL set"; return 1; }

    local alias key_name
    alias="$(workbench_ssh_alias "${name}")"
    key_name="$(workbench_ssh_key_name "${name}")"

    if [[ "${url}" == git@"${alias}":* ]]; then
        log_info "${name}: REPO_URL already in alias form — nothing to do"
        return 0
    fi

    local host path
    host="$(workbench_ssh_extract_host "${url}")" || {
        log_error "${name}: could not determine the git host from REPO_URL '${url}' — set it to https://<host>/..., git@<host>:..., or ssh://git@<host>/... form"
        return 1
    }
    path="$(workbench_ssh_extract_path "${url}")" || {
        log_error "${name}: could not determine the repo path from REPO_URL '${url}'"
        return 1
    }

    local key_path="${HOME}/.ssh/${key_name}"
    local key_is_new="false"
    [[ -f "${key_path}" ]] || key_is_new="true"

    workbench_ssh_generate_deploy_key "${key_name}" "${key_name}@$(hostname 2>/dev/null || echo workbench)"

    if [[ "${key_is_new}" == "true" && -f "${key_path}.pub" ]]; then
        printf '\nACTION REQUIRED for %s — add this deploy key (read-only, allow write access: NO):\n' "${name}" >&2
        printf '  %s -> Settings -> Deploy keys -> Add deploy key\n\n' "${host}" >&2
        cat "${key_path}.pub" >&2
        printf '\n' >&2
    fi

    _wb_ssh_ensure_conf_file "${WORKBENCH_SSH_CONFIG_D_FILE}"
    if grep -qx "Host ${alias}" "${WORKBENCH_SSH_CONFIG_D_FILE}" 2>/dev/null; then
        log_info "${name}: SSH alias '${alias}' already present — skipping"
    else
        _wb_ssh_write_host_entry "${alias}" "${key_name}" "${WORKBENCH_SSH_CONFIG_D_FILE}" "${host}"
        log_info "${name}: wrote SSH alias '${alias}' -> ${host}"
    fi

    workbench_ssh_ensure_config_include
    workbench_module_conf_set "${name}" REPO_URL "git@${alias}:${path}"

    printf '%s\n' "${name}"
}

# workbench_ssh_bootstrap_all
# Runs workbench_ssh_bootstrap_module for every registered PRIVATE=true
# module. Clean no-op (prints nothing) if none exist. Prints each module
# name it acted on, and — for any key newly generated — the public key
# content, so `wb install` can show the "add this deploy key" instructions.
workbench_ssh_bootstrap_all() {
    local name acted_any=false
    while IFS= read -r name; do
        [[ -z "${name}" ]] && continue
        local private
        private="$(workbench_module_conf_get "${name}" PRIVATE false)"
        [[ "${private}" == "true" ]] || continue
        acted_any=true
        workbench_ssh_bootstrap_module "${name}"
    done < <(workbench_list_registered_modules)

    [[ "${acted_any}" == "true" ]] || log_info "workbench_ssh_bootstrap_all: no private modules registered — nothing to do"
}
